import type { ExerciseTemplate } from '@/types/models'

function toSearchUrl(query: string) {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`
}

export const SHIELA_EXERCISE_TEMPLATE: ExerciseTemplate = {
  version: 'shiela-v1',
  title: 'Shiela Weekly Sculpt Plan',
  description:
    'Balanced school-friendly routine focused on fat loss, glute sculpting, and sustainable recovery.',
  items: [
    {
      templateItemId: 'mon-warmup-march',
      weekday: 'monday',
      category: 'warmup',
      name: 'March in place or light skips',
      description: 'Start calm and raise temperature before loading lower body.',
      target: '3-5 minutes',
      videoSearchQuery: 'light march warm up routine',
      videoUrl: toSearchUrl('light march warm up routine'),
      displayOrder: 0,
    },
    {
      templateItemId: 'mon-bw-squat',
      weekday: 'monday',
      category: 'warmup',
      name: 'Bodyweight squats',
      description: 'Controlled depth, knees tracking over toes.',
      target: '20 reps',
      videoSearchQuery: 'bodyweight squat beginner form',
      videoUrl: toSearchUrl('bodyweight squat beginner form'),
      displayOrder: 1,
    },
    {
      templateItemId: 'mon-glute-bridge-primer',
      weekday: 'monday',
      category: 'warmup',
      name: 'Glute bridge primer',
      description: 'Squeeze glutes at the top before main work.',
      target: '15 reps',
      videoSearchQuery: 'glute bridge proper form',
      videoUrl: toSearchUrl('glute bridge proper form'),
      displayOrder: 2,
    },
    {
      templateItemId: 'mon-banded-squat',
      weekday: 'monday',
      category: 'workout',
      name: 'Banded squats',
      description: 'Main glute and leg strength block.',
      target: '3 sets x 12-15 reps',
      videoSearchQuery: 'resistance band squat tutorial',
      videoUrl: toSearchUrl('resistance band squat tutorial'),
      displayOrder: 3,
    },
    {
      templateItemId: 'mon-glute-bridge-work',
      weekday: 'monday',
      category: 'workout',
      name: 'Glute bridges',
      description: 'Drive through heels and avoid overextending lower back.',
      target: '4 sets x 15 reps',
      videoSearchQuery: 'glute bridge proper form',
      videoUrl: toSearchUrl('glute bridge proper form'),
      displayOrder: 4,
    },
    {
      templateItemId: 'mon-banded-kickback',
      weekday: 'monday',
      category: 'workout',
      name: 'Banded kickbacks',
      description: 'Keep hips square and control each rep.',
      target: '3 sets x 12 each leg',
      videoSearchQuery: 'banded glute kickback tutorial',
      videoUrl: toSearchUrl('banded glute kickback tutorial'),
      displayOrder: 5,
    },
    {
      templateItemId: 'mon-lateral-band-walk',
      weekday: 'monday',
      category: 'workout',
      name: 'Lateral band walks',
      description: 'Stay low and keep constant band tension.',
      target: '3 sets x 12 steps each side',
      videoSearchQuery: 'lateral band walk glutes',
      videoUrl: toSearchUrl('lateral band walk glutes'),
      displayOrder: 6,
    },
    {
      templateItemId: 'mon-donkey-kicks',
      weekday: 'monday',
      category: 'workout',
      name: 'Donkey kicks',
      description: 'Avoid arching the lower back at lockout.',
      target: '3 sets x 15 each leg',
      videoSearchQuery: 'donkey kicks glute exercise',
      videoUrl: toSearchUrl('donkey kicks glute exercise'),
      displayOrder: 7,
    },
    {
      templateItemId: 'mon-skipping',
      weekday: 'monday',
      category: 'cardio',
      name: 'Moderate skipping',
      description: 'Finish with controlled cardio, not an all-out sprint.',
      target: '300-500 skips',
      videoSearchQuery: 'jump rope moderate pace form',
      videoUrl: toSearchUrl('jump rope moderate pace form'),
      displayOrder: 8,
    },

    {
      templateItemId: 'tue-cardio',
      weekday: 'tuesday',
      category: 'cardio',
      name: 'Light cardio block',
      description: 'Choose one: easy skipping or brisk walk.',
      target: '500-800 skips or 20-30 min walk',
      videoSearchQuery: 'beginner jump rope or brisk walking technique',
      videoUrl: toSearchUrl('beginner jump rope or brisk walking technique'),
      displayOrder: 0,
    },
    {
      templateItemId: 'tue-plank',
      weekday: 'tuesday',
      category: 'core',
      name: 'Plank',
      description: 'Brace core and keep hips level.',
      target: '3 rounds x 20-30 sec',
      videoSearchQuery: 'beginner plank form',
      videoUrl: toSearchUrl('beginner plank form'),
      displayOrder: 1,
    },
    {
      templateItemId: 'tue-dead-bug',
      weekday: 'tuesday',
      category: 'core',
      name: 'Dead bug',
      description: 'Slow tempo and lower-back contact with floor.',
      target: '3 sets x 10 each side',
      videoSearchQuery: 'dead bug exercise tutorial',
      videoUrl: toSearchUrl('dead bug exercise tutorial'),
      displayOrder: 2,
    },
    {
      templateItemId: 'tue-leg-raise',
      weekday: 'tuesday',
      category: 'core',
      name: 'Leg raises',
      description: 'Control the lowering phase.',
      target: '3 sets x 10-12 reps',
      videoSearchQuery: 'leg raise proper form',
      videoUrl: toSearchUrl('leg raise proper form'),
      displayOrder: 3,
    },

    {
      templateItemId: 'wed-easy-skip',
      weekday: 'wednesday',
      category: 'warmup',
      name: 'Easy skipping warm-up',
      description: 'Keep this easy before strength work.',
      target: '3 minutes',
      videoSearchQuery: 'easy jump rope warm up',
      videoUrl: toSearchUrl('easy jump rope warm up'),
      displayOrder: 0,
    },
    {
      templateItemId: 'wed-bridge-primer',
      weekday: 'wednesday',
      category: 'warmup',
      name: 'Glute bridge warm-up',
      description: 'Prime hip extension.',
      target: '15 reps',
      videoSearchQuery: 'glute bridge proper form',
      videoUrl: toSearchUrl('glute bridge proper form'),
      displayOrder: 1,
    },
    {
      templateItemId: 'wed-reverse-lunge-primer',
      weekday: 'wednesday',
      category: 'warmup',
      name: 'Reverse lunge warm-up',
      description: 'Prepare unilateral leg control.',
      target: '10 each leg',
      videoSearchQuery: 'reverse lunge tutorial',
      videoUrl: toSearchUrl('reverse lunge tutorial'),
      displayOrder: 2,
    },
    {
      templateItemId: 'wed-banded-rdl',
      weekday: 'wednesday',
      category: 'workout',
      name: 'Banded Romanian deadlifts',
      description: 'Hinge from hips and keep spine long.',
      target: '4 sets x 12 reps',
      videoSearchQuery: 'banded romanian deadlift tutorial',
      videoUrl: toSearchUrl('banded romanian deadlift tutorial'),
      displayOrder: 3,
    },
    {
      templateItemId: 'wed-bulgarian',
      weekday: 'wednesday',
      category: 'workout',
      name: 'Bulgarian split squats or reverse lunges',
      description: 'Choose stable option and own each rep.',
      target: '3 sets x 10 each leg',
      videoSearchQuery: 'bulgarian split squat beginner',
      videoUrl: toSearchUrl('bulgarian split squat beginner'),
      displayOrder: 4,
    },
    {
      templateItemId: 'wed-bridge-hold',
      weekday: 'wednesday',
      category: 'workout',
      name: 'Glute bridge with hold',
      description: 'Pause and squeeze hard at the top.',
      target: '3 sets x 12 reps (2s hold)',
      videoSearchQuery: 'glute bridge hold exercise',
      videoUrl: toSearchUrl('glute bridge hold exercise'),
      displayOrder: 5,
    },
    {
      templateItemId: 'wed-diagonal-kickback',
      weekday: 'wednesday',
      category: 'workout',
      name: 'Standing diagonal kickbacks',
      description: 'Diagonal line for glute med engagement.',
      target: '3 sets x 12 each leg',
      videoSearchQuery: 'standing diagonal kickback band',
      videoUrl: toSearchUrl('standing diagonal kickback band'),
      displayOrder: 6,
    },
    {
      templateItemId: 'wed-lateral-walk',
      weekday: 'wednesday',
      category: 'workout',
      name: 'Lateral band walks',
      description: 'Slow controlled lateral steps.',
      target: '2-3 sets x 10 each side',
      videoSearchQuery: 'lateral band walk glutes',
      videoUrl: toSearchUrl('lateral band walk glutes'),
      displayOrder: 7,
    },
    {
      templateItemId: 'wed-optional-cardio',
      weekday: 'wednesday',
      category: 'cardio',
      name: 'Optional moderate skipping',
      description: 'Only if energy is still strong after workout.',
      target: '300-500 skips',
      videoSearchQuery: 'jump rope moderate pace form',
      videoUrl: toSearchUrl('jump rope moderate pace form'),
      displayOrder: 8,
    },

    {
      templateItemId: 'thu-recovery-choice',
      weekday: 'thursday',
      category: 'recovery',
      name: 'Recovery choice block',
      description: 'Choose walk, light skips, or stretch flow.',
      target: '20-30 min walk or 300 light skips or 10-15 min stretch',
      videoSearchQuery: 'active recovery routine beginner',
      videoUrl: toSearchUrl('active recovery routine beginner'),
      displayOrder: 0,
    },
    {
      templateItemId: 'thu-mobility',
      weekday: 'thursday',
      category: 'mobility',
      name: 'Mobility reset',
      description: 'Hamstrings, quads, glutes, and hips.',
      target: '8-12 minutes total',
      videoSearchQuery: 'hip mobility beginner glute stretch routine',
      videoUrl: toSearchUrl('hip mobility beginner glute stretch routine'),
      displayOrder: 1,
    },

    {
      templateItemId: 'fri-easy-move',
      weekday: 'friday',
      category: 'warmup',
      name: 'Easy movement warm-up',
      description: 'Reset before final glute session.',
      target: '3-5 minutes',
      videoSearchQuery: 'lower body warm up no equipment',
      videoUrl: toSearchUrl('lower body warm up no equipment'),
      displayOrder: 0,
    },
    {
      templateItemId: 'fri-air-squat',
      weekday: 'friday',
      category: 'warmup',
      name: 'Air squats',
      description: 'Controlled squat pattern prep.',
      target: '20 reps',
      videoSearchQuery: 'bodyweight squat beginner form',
      videoUrl: toSearchUrl('bodyweight squat beginner form'),
      displayOrder: 1,
    },
    {
      templateItemId: 'fri-bridge-primer',
      weekday: 'friday',
      category: 'warmup',
      name: 'Glute bridge warm-up',
      description: 'Prime posterior chain.',
      target: '15 reps',
      videoSearchQuery: 'glute bridge proper form',
      videoUrl: toSearchUrl('glute bridge proper form'),
      displayOrder: 2,
    },
    {
      templateItemId: 'fri-banded-squat',
      weekday: 'friday',
      category: 'workout',
      name: 'Banded squats',
      description: 'Main lower body volume.',
      target: '3 sets x 15 reps',
      videoSearchQuery: 'resistance band squat tutorial',
      videoUrl: toSearchUrl('resistance band squat tutorial'),
      displayOrder: 3,
    },
    {
      templateItemId: 'fri-banded-rdl',
      weekday: 'friday',
      category: 'workout',
      name: 'Banded RDLs',
      description: 'Slow hinge and strong glute finish.',
      target: '3 sets x 12 reps',
      videoSearchQuery: 'banded rdl form',
      videoUrl: toSearchUrl('banded rdl form'),
      displayOrder: 4,
    },
    {
      templateItemId: 'fri-donkey',
      weekday: 'friday',
      category: 'workout',
      name: 'Donkey kicks',
      description: 'Control and squeeze each side.',
      target: '3 sets x 15 each leg',
      videoSearchQuery: 'donkey kicks glute tutorial',
      videoUrl: toSearchUrl('donkey kicks glute tutorial'),
      displayOrder: 5,
    },
    {
      templateItemId: 'fri-fire-hydrant',
      weekday: 'friday',
      category: 'workout',
      name: 'Fire hydrants or side abductions',
      description: 'Choose one accessory movement.',
      target: '3 sets x 15 each side',
      videoSearchQuery: 'fire hydrant exercise form side lying hip abduction tutorial',
      videoUrl: toSearchUrl('fire hydrant exercise form side lying hip abduction tutorial'),
      displayOrder: 6,
    },
    {
      templateItemId: 'fri-bridge-burnout',
      weekday: 'friday',
      category: 'workout',
      name: 'Glute bridge burnout',
      description: 'Final high-rep squeeze finisher.',
      target: '1 set x 25 reps',
      videoSearchQuery: 'glute bridge proper form',
      videoUrl: toSearchUrl('glute bridge proper form'),
      displayOrder: 7,
    },
    {
      templateItemId: 'fri-cardio',
      weekday: 'friday',
      category: 'cardio',
      name: 'Moderate skipping',
      description: 'Controlled finish, not max intensity.',
      target: '300-500 skips',
      videoSearchQuery: 'jump rope moderate pace form',
      videoUrl: toSearchUrl('jump rope moderate pace form'),
      displayOrder: 8,
    },

    {
      templateItemId: 'sat-bodyweight-squat',
      weekday: 'saturday',
      category: 'full-body',
      name: 'Bodyweight squats',
      description: 'Light full-body day starts here.',
      target: '2 sets x 20 reps',
      videoSearchQuery: 'bodyweight squat beginner',
      videoUrl: toSearchUrl('bodyweight squat beginner'),
      displayOrder: 0,
    },
    {
      templateItemId: 'sat-reverse-lunge',
      weekday: 'saturday',
      category: 'full-body',
      name: 'Reverse lunges',
      description: 'Smooth reps and stable core.',
      target: '2 sets x 10 each leg',
      videoSearchQuery: 'reverse lunge tutorial',
      videoUrl: toSearchUrl('reverse lunge tutorial'),
      displayOrder: 1,
    },
    {
      templateItemId: 'sat-wall-pushup',
      weekday: 'saturday',
      category: 'full-body',
      name: 'Wall or incline push-ups',
      description: 'Upper-body touch without heavy fatigue.',
      target: '2 sets x 10 reps',
      videoSearchQuery: 'wall push up tutorial',
      videoUrl: toSearchUrl('wall push up tutorial'),
      displayOrder: 2,
    },
    {
      templateItemId: 'sat-plank',
      weekday: 'saturday',
      category: 'core',
      name: 'Plank',
      description: 'Short core reinforcement.',
      target: '2 rounds',
      videoSearchQuery: 'plank beginner form',
      videoUrl: toSearchUrl('plank beginner form'),
      displayOrder: 3,
    },
    {
      templateItemId: 'sat-bridge',
      weekday: 'saturday',
      category: 'full-body',
      name: 'Glute bridge',
      description: 'Keep glutes active on light day.',
      target: '2 sets x 20 reps',
      videoSearchQuery: 'glute bridge proper form',
      videoUrl: toSearchUrl('glute bridge proper form'),
      displayOrder: 4,
    },
    {
      templateItemId: 'sat-lateral-walk',
      weekday: 'saturday',
      category: 'full-body',
      name: 'Lateral band walk',
      description: 'Short glute finisher.',
      target: '2 sets each side',
      videoSearchQuery: 'lateral band walk glutes',
      videoUrl: toSearchUrl('lateral band walk glutes'),
      displayOrder: 5,
    },
    {
      templateItemId: 'sat-cardio',
      weekday: 'saturday',
      category: 'cardio',
      name: 'Cardio option',
      description: 'Choose skipping or a brisk walk.',
      target: '500 skips or 20-minute walk',
      videoSearchQuery: 'jump rope beginner or brisk walk cadence',
      videoUrl: toSearchUrl('jump rope beginner or brisk walk cadence'),
      displayOrder: 6,
    },

    {
      templateItemId: 'sun-rest',
      weekday: 'sunday',
      category: 'recovery',
      name: 'Full rest day',
      description: 'No hard training. Optional easy walk only.',
      target: 'Recovery focus',
      videoSearchQuery: 'active recovery walking routine',
      videoUrl: toSearchUrl('active recovery walking routine'),
      displayOrder: 0,
    },
  ],
}

export function getDefaultExerciseTemplate() {
  return {
    ...SHIELA_EXERCISE_TEMPLATE,
    items: SHIELA_EXERCISE_TEMPLATE.items.map((item) => ({ ...item })),
  }
}