import type { ExerciseTemplate } from '@/types/models'

function toSearchUrl(query: string) {
  return `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`
}

export const SHIELA_EXERCISE_TEMPLATE: ExerciseTemplate = {
  templateId: 'shiela-v2',
  version: 'shiela-v2',
  title: 'Shiela Weekly Sculpt Plan',
  description:
    'Structured weekly routine with core activation, banded lower-body work, cardio skips, and rest/recovery.',
  items: [
    {
      templateItemId: 'mon-stomach-vacuums',
      weekday: 'monday',
      category: 'core',
      name: 'Stomach Vacuums',
      description: 'Stand tall, exhale fully, and brace the deep core with controlled breathing.',
      target: '5 sets x 20-second holds',
      videoSearchQuery: 'stomach vacuum exercise tutorial',
      videoUrl: toSearchUrl('stomach vacuum exercise tutorial'),
      displayOrder: 0,
    },
    {
      templateItemId: 'mon-skips-1000',
      weekday: 'monday',
      category: 'cardio',
      name: 'Skips',
      description: 'Steady pace jump-rope volume.',
      target: '1,000 skips',
      videoSearchQuery: 'jump rope form beginner',
      videoUrl: toSearchUrl('jump rope form beginner'),
      displayOrder: 1,
    },
    {
      templateItemId: 'mon-banded-squats-heavy',
      weekday: 'monday',
      category: 'workout',
      name: 'Banded Squats',
      description: 'Band placement: heavy band above knees.',
      target: '3 sets x 15 reps',
      videoSearchQuery: 'banded squats heavy band above knees',
      videoUrl: toSearchUrl('banded squats heavy band above knees'),
      displayOrder: 2,
    },
    {
      templateItemId: 'mon-banded-glute-bridges-heavy',
      weekday: 'monday',
      category: 'workout',
      name: 'Banded Glute Bridges',
      description: 'Band placement: heavy band above knees.',
      target: '3 sets x 20 reps',
      videoSearchQuery: 'banded glute bridge heavy band above knees',
      videoUrl: toSearchUrl('banded glute bridge heavy band above knees'),
      displayOrder: 3,
    },
    {
      templateItemId: 'mon-reverse-lunges',
      weekday: 'monday',
      category: 'workout',
      name: 'Reverse Lunges',
      description: 'Control knee alignment and step back softly.',
      target: '3 sets x 12 reps per leg',
      videoSearchQuery: 'reverse lunge exercise form',
      videoUrl: toSearchUrl('reverse lunge exercise form'),
      displayOrder: 4,
    },

    {
      templateItemId: 'tue-stomach-vacuums',
      weekday: 'tuesday',
      category: 'core',
      name: 'Stomach Vacuums',
      description: 'Stand tall, exhale fully, and brace the deep core with controlled breathing.',
      target: '5 sets x 20-second holds',
      videoSearchQuery: 'stomach vacuum exercise tutorial',
      videoUrl: toSearchUrl('stomach vacuum exercise tutorial'),
      displayOrder: 0,
    },
    {
      templateItemId: 'tue-skips-1000',
      weekday: 'tuesday',
      category: 'cardio',
      name: 'Skips',
      description: 'Steady pace jump-rope volume.',
      target: '1,000 skips',
      videoSearchQuery: 'jump rope form beginner',
      videoUrl: toSearchUrl('jump rope form beginner'),
      displayOrder: 1,
    },
    {
      templateItemId: 'tue-banded-fire-hydrants',
      weekday: 'tuesday',
      category: 'workout',
      name: 'Banded Fire Hydrants',
      description: 'Band placement: medium band above knees.',
      target: '3 sets x 20 reps per leg',
      videoSearchQuery: 'banded fire hydrants medium band above knees',
      videoUrl: toSearchUrl('banded fire hydrants medium band above knees'),
      displayOrder: 2,
    },
    {
      templateItemId: 'tue-banded-clamshells-heavy',
      weekday: 'tuesday',
      category: 'workout',
      name: 'Banded Clamshells',
      description: 'Band placement: heavy band above knees.',
      target: '3 sets x 20 reps per side',
      videoSearchQuery: 'banded clamshells heavy band above knees',
      videoUrl: toSearchUrl('banded clamshells heavy band above knees'),
      displayOrder: 3,
    },
    {
      templateItemId: 'tue-standing-side-kicks',
      weekday: 'tuesday',
      category: 'workout',
      name: 'Standing Side Kicks',
      description: 'Band placement: medium band around ankles.',
      target: '3 sets x 15 reps per leg',
      videoSearchQuery: 'standing side kicks resistance band ankles',
      videoUrl: toSearchUrl('standing side kicks resistance band ankles'),
      displayOrder: 4,
    },

    {
      templateItemId: 'wed-stomach-vacuums',
      weekday: 'wednesday',
      category: 'core',
      name: 'Stomach Vacuums',
      description: 'Stand tall, exhale fully, and brace the deep core with controlled breathing.',
      target: '5 sets x 20-second holds',
      videoSearchQuery: 'stomach vacuum exercise tutorial',
      videoUrl: toSearchUrl('stomach vacuum exercise tutorial'),
      displayOrder: 0,
    },
    {
      templateItemId: 'wed-skips-1000',
      weekday: 'wednesday',
      category: 'cardio',
      name: 'Skips',
      description: 'Steady pace jump-rope volume.',
      target: '1,000 skips',
      videoSearchQuery: 'jump rope form beginner',
      videoUrl: toSearchUrl('jump rope form beginner'),
      displayOrder: 1,
    },
    {
      templateItemId: 'wed-banded-dead-bugs',
      weekday: 'wednesday',
      category: 'core',
      name: 'Banded Dead Bugs',
      description: 'Band placement: light or medium band around feet.',
      target: '3 sets x 15 reps total',
      videoSearchQuery: 'banded dead bug around feet',
      videoUrl: toSearchUrl('banded dead bug around feet'),
      displayOrder: 2,
    },
    {
      templateItemId: 'wed-banded-plank-taps',
      weekday: 'wednesday',
      category: 'core',
      name: 'Banded Plank Taps',
      description: 'Band placement: medium band around ankles.',
      target: '3 sets x 20 taps total',
      videoSearchQuery: 'banded plank taps around ankles',
      videoUrl: toSearchUrl('banded plank taps around ankles'),
      displayOrder: 3,
    },
    {
      templateItemId: 'wed-banded-donkey-kicks-heavy',
      weekday: 'wednesday',
      category: 'workout',
      name: 'Banded Donkey Kicks',
      description: 'Band placement: heavy above knees or in the crook of working knee.',
      target: '3 sets x 15 reps per leg',
      videoSearchQuery: 'banded donkey kicks heavy band',
      videoUrl: toSearchUrl('banded donkey kicks heavy band'),
      displayOrder: 4,
    },

    {
      templateItemId: 'thu-stomach-vacuums',
      weekday: 'thursday',
      category: 'core',
      name: 'Stomach Vacuums',
      description: 'Stand tall, exhale fully, and brace the deep core with controlled breathing.',
      target: '5 sets x 20-second holds',
      videoSearchQuery: 'stomach vacuum exercise tutorial',
      videoUrl: toSearchUrl('stomach vacuum exercise tutorial'),
      displayOrder: 0,
    },
    {
      templateItemId: 'thu-skips-1000',
      weekday: 'thursday',
      category: 'cardio',
      name: 'Skips',
      description: 'Steady pace jump-rope volume.',
      target: '1,000 skips',
      videoSearchQuery: 'jump rope form beginner',
      videoUrl: toSearchUrl('jump rope form beginner'),
      displayOrder: 1,
    },
    {
      templateItemId: 'thu-banded-kickbacks-medium',
      weekday: 'thursday',
      category: 'workout',
      name: 'Banded Kickbacks',
      description: 'Band placement: medium band around ankles.',
      target: '3 sets x 15 reps per leg',
      videoSearchQuery: 'banded kickbacks medium band around ankles',
      videoUrl: toSearchUrl('banded kickbacks medium band around ankles'),
      displayOrder: 2,
    },
    {
      templateItemId: 'thu-banded-glute-bridges-heavy-hold',
      weekday: 'thursday',
      category: 'workout',
      name: 'Banded Glute Bridges',
      description: 'Band placement: heavy band above knees. Hold last rep for 10 seconds.',
      target: '3 sets x 20 reps',
      videoSearchQuery: 'banded glute bridge hold last rep',
      videoUrl: toSearchUrl('banded glute bridge hold last rep'),
      displayOrder: 3,
    },
    {
      templateItemId: 'thu-banded-clamshells-heavy',
      weekday: 'thursday',
      category: 'workout',
      name: 'Banded Clamshells',
      description: 'Band placement: heavy band above knees.',
      target: '3 sets x 15 reps per side',
      videoSearchQuery: 'banded clamshells heavy band above knees',
      videoUrl: toSearchUrl('banded clamshells heavy band above knees'),
      displayOrder: 4,
    },

    {
      templateItemId: 'fri-stomach-vacuums',
      weekday: 'friday',
      category: 'core',
      name: 'Stomach Vacuums',
      description: 'Stand tall, exhale fully, and brace the deep core with controlled breathing.',
      target: '5 sets x 20-second holds',
      videoSearchQuery: 'stomach vacuum exercise tutorial',
      videoUrl: toSearchUrl('stomach vacuum exercise tutorial'),
      displayOrder: 0,
    },
    {
      templateItemId: 'fri-skips-1000',
      weekday: 'friday',
      category: 'cardio',
      name: 'Skips',
      description: 'Steady pace jump-rope volume.',
      target: '1,000 skips',
      videoSearchQuery: 'jump rope form beginner',
      videoUrl: toSearchUrl('jump rope form beginner'),
      displayOrder: 1,
    },
    {
      templateItemId: 'fri-banded-squats-heavy-slow',
      weekday: 'friday',
      category: 'workout',
      name: 'Banded Squats',
      description: 'Band placement: heavy band above knees. Perform each rep very slowly.',
      target: '3 sets x 12 reps',
      videoSearchQuery: 'slow banded squats heavy band above knees',
      videoUrl: toSearchUrl('slow banded squats heavy band above knees'),
      displayOrder: 2,
    },
    {
      templateItemId: 'fri-fire-hydrants-medium',
      weekday: 'friday',
      category: 'workout',
      name: 'Fire Hydrants',
      description: 'Band placement: medium band above knees.',
      target: '3 sets x 15 reps per side',
      videoSearchQuery: 'fire hydrants medium band above knees',
      videoUrl: toSearchUrl('fire hydrants medium band above knees'),
      displayOrder: 3,
    },
    {
      templateItemId: 'fri-donkey-kicks-heavy',
      weekday: 'friday',
      category: 'workout',
      name: 'Donkey Kicks',
      description: 'Band placement: heavy band above knees.',
      target: '3 sets x 15 reps per side',
      videoSearchQuery: 'donkey kicks heavy band above knees',
      videoUrl: toSearchUrl('donkey kicks heavy band above knees'),
      displayOrder: 4,
    },
    {
      templateItemId: 'fri-banded-plank-taps-medium',
      weekday: 'friday',
      category: 'core',
      name: 'Banded Plank Taps',
      description: 'Band placement: medium band around ankles.',
      target: '3 sets x 20 reps',
      videoSearchQuery: 'banded plank taps around ankles',
      videoUrl: toSearchUrl('banded plank taps around ankles'),
      displayOrder: 5,
    },

    {
      templateItemId: 'sat-steps-10000',
      weekday: 'saturday',
      category: 'cardio',
      name: 'Steps',
      description: 'Low-impact fat-burn walk day.',
      target: '10,000 steps',
      videoSearchQuery: 'how to walk 10000 steps in a day',
      videoUrl: toSearchUrl('how to walk 10000 steps in a day'),
      displayOrder: 0,
    },

    {
      templateItemId: 'sun-rest',
      weekday: 'sunday',
      category: 'recovery',
      name: 'Full rest day',
      description: 'Full rest day.',
      target: 'No training',
      videoSearchQuery: 'rest day recovery tips',
      videoUrl: toSearchUrl('rest day recovery tips'),
      displayOrder: 0,
    },
  ],
}

export const MALE_BUILD_EXERCISE_TEMPLATE: ExerciseTemplate = {
  templateId: 'male-v1',
  version: 'male-v1',
  title: 'Male Build Weekly Split',
  description:
    'Intermediate 5-day dumbbell and calisthenics split for chest, shoulders, arms, legs, and abs.',
  items: [
    {
      templateItemId: 'male-mon-db-press',
      weekday: 'monday',
      category: 'workout',
      name: 'Dumbbell Floor or Bench Press',
      description: 'Primary chest press. Add load gradually while maintaining control.',
      target: '4 sets x 8-12 reps',
      videoSearchQuery: 'dumbbell bench press proper form',
      videoUrl: toSearchUrl('dumbbell bench press proper form'),
      displayOrder: 0,
    },
    {
      templateItemId: 'male-mon-pushups',
      weekday: 'monday',
      category: 'workout',
      name: 'Push-Ups',
      description: 'Keep ribs down and full lockout each rep.',
      target: '3 sets x 12-20 reps',
      videoSearchQuery: 'push up form chest triceps',
      videoUrl: toSearchUrl('push up form chest triceps'),
      displayOrder: 1,
    },
    {
      templateItemId: 'male-mon-db-fly-press',
      weekday: 'monday',
      category: 'workout',
      name: 'Dumbbell Fly to Press',
      description: 'Control stretch and avoid shoulder shrugging.',
      target: '3 sets x 10-12 reps',
      videoSearchQuery: 'dumbbell fly press variation',
      videoUrl: toSearchUrl('dumbbell fly press variation'),
      displayOrder: 2,
    },
    {
      templateItemId: 'male-mon-oh-triceps',
      weekday: 'monday',
      category: 'workout',
      name: 'Overhead Dumbbell Triceps Extension',
      description: 'Elbows stable and close to head.',
      target: '3 sets x 10-15 reps',
      videoSearchQuery: 'overhead dumbbell triceps extension form',
      videoUrl: toSearchUrl('overhead dumbbell triceps extension form'),
      displayOrder: 3,
    },
    {
      templateItemId: 'male-mon-bench-dips',
      weekday: 'monday',
      category: 'workout',
      name: 'Bench or Chair Dips',
      description: 'Use controlled depth and avoid shoulder collapse.',
      target: '3 sets x 10-15 reps',
      videoSearchQuery: 'bench dips proper form',
      videoUrl: toSearchUrl('bench dips proper form'),
      displayOrder: 4,
    },
    {
      templateItemId: 'male-mon-core-finisher',
      weekday: 'monday',
      category: 'core',
      name: 'Plank + Leg Raises',
      description: 'Alternate plank hold and strict leg raise sets.',
      target: '3 rounds: 45s plank + 12 leg raises',
      videoSearchQuery: 'plank and lying leg raise workout',
      videoUrl: toSearchUrl('plank and lying leg raise workout'),
      displayOrder: 5,
    },

    {
      templateItemId: 'male-tue-goblet-squat',
      weekday: 'tuesday',
      category: 'workout',
      name: 'Goblet Squats',
      description: 'Brace core and hit full controlled depth.',
      target: '4 sets x 8-12 reps',
      videoSearchQuery: 'goblet squat form',
      videoUrl: toSearchUrl('goblet squat form'),
      displayOrder: 0,
    },
    {
      templateItemId: 'male-tue-db-rdl',
      weekday: 'tuesday',
      category: 'workout',
      name: 'Dumbbell Romanian Deadlift',
      description: 'Hip hinge with long spine and soft knees.',
      target: '4 sets x 8-12 reps',
      videoSearchQuery: 'dumbbell romanian deadlift form',
      videoUrl: toSearchUrl('dumbbell romanian deadlift form'),
      displayOrder: 1,
    },
    {
      templateItemId: 'male-tue-reverse-lunge',
      weekday: 'tuesday',
      category: 'workout',
      name: 'Reverse Lunges',
      description: 'Step back softly and keep front knee stable.',
      target: '3 sets x 10-12 reps per leg',
      videoSearchQuery: 'reverse lunge with dumbbells form',
      videoUrl: toSearchUrl('reverse lunge with dumbbells form'),
      displayOrder: 2,
    },
    {
      templateItemId: 'male-tue-calf-raise',
      weekday: 'tuesday',
      category: 'workout',
      name: 'Standing Calf Raises',
      description: 'Pause at top and lower slowly.',
      target: '4 sets x 12-20 reps',
      videoSearchQuery: 'standing calf raises form',
      videoUrl: toSearchUrl('standing calf raises form'),
      displayOrder: 3,
    },
    {
      templateItemId: 'male-tue-hollow-hold',
      weekday: 'tuesday',
      category: 'core',
      name: 'Hollow Hold',
      description: 'Keep lower back pressed to the floor.',
      target: '3 sets x 30-45 seconds',
      videoSearchQuery: 'hollow hold abs form',
      videoUrl: toSearchUrl('hollow hold abs form'),
      displayOrder: 4,
    },
    {
      templateItemId: 'male-tue-bicycle-crunch',
      weekday: 'tuesday',
      category: 'core',
      name: 'Bicycle Crunches',
      description: 'Rotate from core, not neck pull.',
      target: '3 sets x 20-30 total reps',
      videoSearchQuery: 'bicycle crunch proper form',
      videoUrl: toSearchUrl('bicycle crunch proper form'),
      displayOrder: 5,
    },

    {
      templateItemId: 'male-wed-db-shoulder-press',
      weekday: 'wednesday',
      category: 'workout',
      name: 'Dumbbell Shoulder Press',
      description: 'Press vertically with controlled tempo.',
      target: '4 sets x 8-12 reps',
      videoSearchQuery: 'dumbbell shoulder press form',
      videoUrl: toSearchUrl('dumbbell shoulder press form'),
      displayOrder: 0,
    },
    {
      templateItemId: 'male-wed-lateral-raise',
      weekday: 'wednesday',
      category: 'workout',
      name: 'Lateral Raises',
      description: 'Lead with elbows and avoid swinging.',
      target: '4 sets x 12-15 reps',
      videoSearchQuery: 'dumbbell lateral raise form',
      videoUrl: toSearchUrl('dumbbell lateral raise form'),
      displayOrder: 1,
    },
    {
      templateItemId: 'male-wed-rear-delt-raise',
      weekday: 'wednesday',
      category: 'workout',
      name: 'Rear Delt Raises',
      description: 'Hinge slightly and squeeze upper back.',
      target: '3 sets x 12-15 reps',
      videoSearchQuery: 'rear delt dumbbell raise form',
      videoUrl: toSearchUrl('rear delt dumbbell raise form'),
      displayOrder: 2,
    },
    {
      templateItemId: 'male-wed-alt-curl',
      weekday: 'wednesday',
      category: 'workout',
      name: 'Alternating Dumbbell Curls',
      description: 'Keep elbows pinned and full range each arm.',
      target: '3 sets x 10-12 reps per arm',
      videoSearchQuery: 'alternating dumbbell curls form',
      videoUrl: toSearchUrl('alternating dumbbell curls form'),
      displayOrder: 3,
    },
    {
      templateItemId: 'male-wed-hammer-curl',
      weekday: 'wednesday',
      category: 'workout',
      name: 'Hammer Curls',
      description: 'Neutral grip, no torso swing.',
      target: '3 sets x 10-12 reps',
      videoSearchQuery: 'hammer curls proper form',
      videoUrl: toSearchUrl('hammer curls proper form'),
      displayOrder: 4,
    },
    {
      templateItemId: 'male-wed-close-grip-pushups',
      weekday: 'wednesday',
      category: 'workout',
      name: 'Close-Grip Push-Ups',
      description: 'Hands narrow to emphasize triceps and chest.',
      target: '3 sets x 10-15 reps',
      videoSearchQuery: 'close grip push up form',
      videoUrl: toSearchUrl('close grip push up form'),
      displayOrder: 5,
    },

    {
      templateItemId: 'male-thu-incline-pushups',
      weekday: 'thursday',
      category: 'workout',
      name: 'Incline Push-Ups',
      description: 'Controlled chest volume with clean form.',
      target: '4 sets x 12-20 reps',
      videoSearchQuery: 'incline push up proper form',
      videoUrl: toSearchUrl('incline push up proper form'),
      displayOrder: 0,
    },
    {
      templateItemId: 'male-thu-db-press-variation',
      weekday: 'thursday',
      category: 'workout',
      name: 'Dumbbell Press Variation',
      description: 'Use neutral or incline angle variation for chest stimulus.',
      target: '4 sets x 8-12 reps',
      videoSearchQuery: 'dumbbell chest press variation',
      videoUrl: toSearchUrl('dumbbell chest press variation'),
      displayOrder: 1,
    },
    {
      templateItemId: 'male-thu-pike-pushups',
      weekday: 'thursday',
      category: 'workout',
      name: 'Pike Push-Ups',
      description: 'Shoulder-dominant pressing with hips high.',
      target: '3 sets x 8-12 reps',
      videoSearchQuery: 'pike push up form',
      videoUrl: toSearchUrl('pike push up form'),
      displayOrder: 2,
    },
    {
      templateItemId: 'male-thu-arnold-press',
      weekday: 'thursday',
      category: 'workout',
      name: 'Arnold Press',
      description: 'Smooth rotational press through full range.',
      target: '3 sets x 10-12 reps',
      videoSearchQuery: 'arnold press form dumbbell',
      videoUrl: toSearchUrl('arnold press form dumbbell'),
      displayOrder: 3,
    },
    {
      templateItemId: 'male-thu-side-plank',
      weekday: 'thursday',
      category: 'core',
      name: 'Side Plank',
      description: 'Keep hips stacked and core braced.',
      target: '3 sets x 30-45 seconds each side',
      videoSearchQuery: 'side plank form',
      videoUrl: toSearchUrl('side plank form'),
      displayOrder: 4,
    },
    {
      templateItemId: 'male-thu-mountain-climbers',
      weekday: 'thursday',
      category: 'core',
      name: 'Mountain Climbers',
      description: 'Maintain plank line and controlled speed.',
      target: '3 sets x 30-40 seconds',
      videoSearchQuery: 'mountain climbers exercise form',
      videoUrl: toSearchUrl('mountain climbers exercise form'),
      displayOrder: 5,
    },

    {
      templateItemId: 'male-fri-split-squats',
      weekday: 'friday',
      category: 'workout',
      name: 'Split Squats',
      description: 'Drive through front foot and stay upright.',
      target: '4 sets x 8-12 reps per leg',
      videoSearchQuery: 'split squat dumbbell form',
      videoUrl: toSearchUrl('split squat dumbbell form'),
      displayOrder: 0,
    },
    {
      templateItemId: 'male-fri-step-ups',
      weekday: 'friday',
      category: 'workout',
      name: 'Dumbbell Step-Ups',
      description: 'Use stable box height and avoid push-off from trailing leg.',
      target: '3 sets x 10-12 reps per leg',
      videoSearchQuery: 'dumbbell step up form',
      videoUrl: toSearchUrl('dumbbell step up form'),
      displayOrder: 1,
    },
    {
      templateItemId: 'male-fri-hip-hinge-glute',
      weekday: 'friday',
      category: 'workout',
      name: 'Hip Hinge Glute Bridge',
      description: 'Glute-focused hinge and squeeze at top.',
      target: '3 sets x 12-15 reps',
      videoSearchQuery: 'dumbbell hip hinge glute bridge',
      videoUrl: toSearchUrl('dumbbell hip hinge glute bridge'),
      displayOrder: 2,
    },
    {
      templateItemId: 'male-fri-curl-to-press',
      weekday: 'friday',
      category: 'workout',
      name: 'Curl-to-Press',
      description: 'Combine strict curl with controlled shoulder press.',
      target: '3 sets x 8-12 reps',
      videoSearchQuery: 'dumbbell curl to press form',
      videoUrl: toSearchUrl('dumbbell curl to press form'),
      displayOrder: 3,
    },
    {
      templateItemId: 'male-fri-triceps-kickbacks',
      weekday: 'friday',
      category: 'workout',
      name: 'Triceps Kickbacks',
      description: 'Hold upper arm fixed and extend fully.',
      target: '3 sets x 12-15 reps',
      videoSearchQuery: 'triceps kickback dumbbell form',
      videoUrl: toSearchUrl('triceps kickback dumbbell form'),
      displayOrder: 4,
    },
    {
      templateItemId: 'male-fri-abs-finisher',
      weekday: 'friday',
      category: 'core',
      name: 'Abs Circuit Finisher',
      description: 'Cycle crunches, leg raises, and plank in one round.',
      target: '3 rounds: 20 crunches, 12 leg raises, 45s plank',
      videoSearchQuery: 'abs circuit crunch leg raise plank',
      videoUrl: toSearchUrl('abs circuit crunch leg raise plank'),
      displayOrder: 5,
    },

    {
      templateItemId: 'male-sat-active-recovery',
      weekday: 'saturday',
      category: 'recovery',
      name: 'Active Recovery Walk + Mobility',
      description: 'Low-intensity movement and mobility work.',
      target: '30-45 minute walk + 10 minute mobility',
      videoSearchQuery: 'active recovery mobility routine',
      videoUrl: toSearchUrl('active recovery mobility routine'),
      displayOrder: 0,
    },
    {
      templateItemId: 'male-sun-full-rest',
      weekday: 'sunday',
      category: 'recovery',
      name: 'Full Rest Day',
      description: 'No structured training. Hydrate and recover.',
      target: 'Recovery focus',
      videoSearchQuery: 'rest day recovery tips',
      videoUrl: toSearchUrl('rest day recovery tips'),
      displayOrder: 0,
    },
  ],
}

const EXERCISE_TEMPLATE_REGISTRY: ExerciseTemplate[] = [
  SHIELA_EXERCISE_TEMPLATE,
  MALE_BUILD_EXERCISE_TEMPLATE,
]

function cloneTemplate(template: ExerciseTemplate): ExerciseTemplate {
  return {
    ...template,
    items: template.items.map((item) => ({ ...item })),
  }
}

export function getExerciseTemplates() {
  return EXERCISE_TEMPLATE_REGISTRY.map(cloneTemplate)
}

export function getExerciseTemplateById(templateId: string) {
  const template = EXERCISE_TEMPLATE_REGISTRY.find((item) => item.templateId === templateId)
  return template ? cloneTemplate(template) : null
}

export function getDefaultExerciseTemplate() {
  return cloneTemplate(SHIELA_EXERCISE_TEMPLATE)
}
